[features]
seeds = false
skip-lint = false
[programs.localnet]
dao = "J8adapkvtdxjhnMLPkiX5sLD2uoALJhkSaXSQ47fR6sJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
